[workspace]
authors = ["Hiroki Tanaka <hiroki.tanaka@ikz-berlin.de>"]
channels = ["conda-forge"]
name = "laser-cooling-app"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
scipy = ">=1.15.2,<2"
seabreeze = ">=2.10.1,<3"
numpy = ">=2.2.6,<3"
pyqtgraph = ">=0.13.7,<0.14"
pip = ">=25.1.1,<26"
pywin32 = ">=311,<312"
matplotlib = ">=3.10.3,<4"
