[workspace]
channels = ["conda-forge"]
name = "laser-cooling-app"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
pip = ">=25.1.1,<26"
pywin32 = ">=311,<312"
pyqtgraph = ">=0.13.7,<0.14"
seabreeze = ">=2.10.1,<3"
numpy = "==1.26.4"
matplotlib = ">=3.10.3,<4"
